name: pedal_application
description: "A new Flutter project."
publish_to: "none"  # Keep it private for now

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0  # Keep this version
  google_maps_flutter_web: ^0.5.10  # Keep this version
  file_picker: ^8.1.4
  location: ^7.0.1 
  cupertino_icons: ^1.0.8
  route_manager: ^2.0.2
  get: ^4.6.6
  http: ^1.2.2 # Make sure it's compatible with Dart SDK
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  geolocator: ^13.0.2
  flutter_polyline_points: ^2.1.0
  flutter_svg: ^2.0.16
  geocoding: ^3.0.0 # or the latest version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/LOGO.png
    - lib/assets/images/car.png
    - lib/assets/logo/logo.png
    - assets/locations.json
    - lib/assets/location-icon/destination.png
    - lib/assets/location-icon/car.png
    
