name: pedal_application
description: "A new Flutter project."
publish_to: "none"  # Keep it private for now

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.10.0  # Update to the latest compatible version
  google_maps_flutter_web: ^0.5.10  # Update to the latest web version
  file_picker: ^8.1.4
  google_maps_webservice: ^0.0.19  # Updated for place search functionality
  location: ^7.0.1
  cupertino_icons: ^1.0.8
  route_manager: ^2.0.2
  get: ^4.6.6
  http: ^0.13.6  # Downgraded to compatible version
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  geolocator: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/LOGO.png
    - lib/assets/images/car.png
    - lib/assets/logo/logo.png
    - assets/locations.json
